### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by seangreathouse** [walkerab/terraform-plus-github-actions#40]
Hey Andrew,
Thanks for the great blog post and project.
If your intent was for this to be open-source, would you mind adding a license to the project?
Preferably a permissive one like Apache 2.0?

**Comment by walkerab** [comment]
Sorry for the late reply. I've added the MIT license which I believe should be permissive enough.

**Comment by seangreathouse** [comment]
Excellent, thanks!
